Travailler avec des vecteurs, des matrices et des tableaux dans NumPy

# Introduction
NumPy est un outil fondamental de la pile Python de machine learning. Il permet d'effectuer des opérations efficaces sur les structures de données fréquemment utilisées en machine learning : vecteurs, matrices et tenseurs. Ce chapitre aborde les opérations NumPy les plus courantes que nous sommes susceptibles de rencontrer lors de nos travaux de machine learning.

# Installation et chargement de NumPy

In [2]:
#Installation et import
#!pip install numpy
import numpy as np


# Création d’un vecteur

On veut créer un vecteur.

Pour ce faire, on utilise NumPy pour créer un tableau unidimensionnel :


In [7]:
# Créer un vecteur comme une ligne
vecteur_ligne = np.array([1, 2, 3])

# Créer un vecteur comme une colonne
vecteur_colonne = np.array([[1],
                            [2],
                            [3]])

La principale structure de données de NumPy est le tableau multidimensionnel. Un vecteur est simplement un tableau avec une seule dimension.
Pour créer un vecteur, on crée donc un tableau unidimensionnel.
Comme les vecteurs, ces tableaux peuvent être représentés horizontalement (c’est-à-dire en lignes) ou verticalement (c’est-à-dire en colonnes).


# Création d’une matrice

On souhaite créer une matrice.

Pour cela, on utilise NumPy pour créer un tableau à deux dimensions :


In [8]:
# Créer une matrice
matrice = np.array([[1, 2],
                    [1, 2],
                    [1, 2]])

Pour créer une matrice, on peut utiliser un tableau à deux dimensions avec NumPy.
Dans notre exemple, la matrice contient trois lignes et deux colonnes (une colonne de 1 et une colonne de 2).
NumPy possède en réalité une structure de données spécifique pour les matrices :
````python
matrice_objet = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])
````

Ce qui donnerait :
```
matrix([[1, 2],
        [1, 2],
        [1, 2]])
```

Cependant, cette structure pour les matrices n’est pas recommandée pour deux raisons :
- Les tableaux (array) sont la structure de données standard utilisée dans NumPy.
- La grande majorité des opérations effectuées avec NumPy retournent des tableaux, et non des objets matrix.



# Création d’une matrice creuse

On dispose de données avec très peu de valeurs non nulles et on veut les représenter efficacement.

On crée donc une matrice creuse :


In [ ]:
#!pip install scipy

In [14]:
# chager la bibliothèque sparse de scipy pour travailler avec des matrices creuses (sparse matrices)
from scipy import sparse

# Créer une matrice
matrice = np.array([[0, 0],
                    [0, 1],
                    [3, 0]])

# Créer une matrice creuse au format CSR (Compressed Sparse Row)
matrice_creuse = sparse.csr_matrix(matrice)

In [15]:
print(matrice_creuse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


En apprentissage automatique, on rencontre souvent de très grandes quantités de données, dont la majorité des éléments sont des zéros.

Par exemple, imaginons une matrice où les colonnes représentent tous les films disponibles sur Netflix, les lignes représentent les utilisateurs, et chaque valeur indique combien de fois un utilisateur a regardé un film donné.
La matrice aurait des dizaines de milliers de colonnes et des millions de lignes ! Mais comme la plupart des gens ne regardent qu’une petite fraction de ces films, l’immense majorité des valeurs serait nulle.

Une matrice creuse est une matrice dans laquelle la plupart des éléments sont à zéro. Ces matrices ne stockent que les valeurs non nulles et supposent que les autres sont des zéros, ce qui permet de gagner en mémoire et en performance.

Dans l’exemple ci-dessus, nous avons créé une matrice NumPy avec deux éléments non nuls, puis nous l’avons convertie en matrice creuse. 
Si on affiche cette matrice :

````python
print(matrice_creuse)
````

Cela donne :
````
  (1, 1)	1
  (2, 0)	3
````

Cela signifie que seuls les éléments non nuls sont stockés :
- Le 1 est à l’indice (1, 1) — deuxième ligne, deuxième colonne
- Le 3 est à l’indice (2, 0) — troisième ligne, première colonne

**Comparaison avec une matrice plus grande**

Si on crée une matrice plus grande, avec beaucoup plus de zéros :

````python
matrice_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                          [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                          [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

matrice_large_creuse = sparse.csr_matrix(matrice_large)

print(matrice_large_creuse)
````

On obtient :
````
  (1, 1)	1
  (2, 0)	3
````

Même avec davantage de colonnes et de zéros, la représentation creuse est identique. Cela montre bien l’intérêt de ce type de structure : la taille en mémoire reste la même tant que les éléments non nuls ne changent pas.

**Types de matrices creuses**

Il existe plusieurs formats de matrices creuses, parmi lesquels :
- CSR (Compressed Sparse Row)
- CSC (Compressed Sparse Column)
- Liste de listes (lil)
- Dictionnaire de clés (dok)

Chaque format a ses avantages et inconvénients. Il n’y a pas de « meilleur » format universel, mais il est important de choisir en fonction du contexte et des opérations à effectuer.


# Préallocation de tableaux NumPy

On est amener à préallouer des tableaux d’une taille donnée avec une certaine valeur.

NumPy propose des fonctions pour générer des vecteurs et des matrices de n’importe quelle taille contenant des zéros, des uns, ou la valeur de au choix :


In [19]:
# Charger la bibliothèque
import numpy as np

# Générer un vecteur de forme (1,5) contenant uniquement des zéros
vecteur = np.zeros(shape=5)

# Afficher le vecteur
print("Résultat de np.zeros(shape=5) : ")
print(vecteur)



Résultat de np.zeros(shape=5) : 
[0. 0. 0. 0. 0.]


In [ ]:
# Générer une matrice de forme (3,3) contenant uniquement des uns
matrice = np.full(shape=(3,3), fill_value=1)

# Afficher la matrice
print("Résultat de np.full(shape=(3,3), fill_value=1) : ")
print(matrice)

Résultat de np.full(shape=(3,3), fill_value=1) : 
[[1 1 1]
 [1 1 1]
 [1 1 1]]


Générer des tableaux préremplis avec des données est utile dans plusieurs cas, comme :
- Améliorer les performances du code
- Créer des données synthétiques pour tester des algorithmes
Dans de nombreux langages de programmation, préallouer un tableau avec des valeurs par défaut (comme des zéros) est une pratique courante pour rendre le code plus stable et plus rapide.


# Sélection d’éléments

On souhaite sélectionner un ou plusieurs éléments dans un vecteur ou une matrice.

Pour ce faire, les tableaux NumPy rendent la sélection d’éléments très simple :


In [22]:
# Créer un vecteur ligne
vecteur = np.array([1, 2, 3, 4, 5, 6])

# Sélectionner le troisième élément du vecteur
vecteur[2]  # Résultat : 3

np.int64(3)

In [23]:
# Créer une matrice
matrice = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Sélectionner l’élément de la deuxième ligne, deuxième colonne
matrice[1, 1]  # Résultat : 5

np.int64(5)

Comme dans la majorité des cas en Python, les tableaux NumPy sont indexés à partir de zéro, c’est-à-dire que le premier élément a l’indice 0.
NumPy offre une grande variété de méthodes pour sélectionner (indexer et découper) des éléments ou groupes d’éléments :
````python
# Sélectionner tous les éléments d’un vecteur
vecteur[:]  # array([1, 2, 3, 4, 5, 6])

# Sélectionner tout jusqu’au troisième élément inclus
vecteur[:3]  # array([1, 2, 3])

# Sélectionner tout à partir du quatrième élément
vecteur[3:]  # array([4, 5, 6])

# Sélectionner le dernier élément
vecteur[-1]  # 6

# Inverser le vecteur
vecteur[::-1]  # array([6, 5, 4, 3, 2, 1])

# Sélectionner les deux premières lignes et toutes les colonnes de la matrice
matrice[:2, :]  
# Résultat : array([[1, 2, 3],
#                  [4, 5, 6]])

# Sélectionner toutes les lignes et la deuxième colonne
matrice[:, 1:2]  
# Résultat : array([[2],
#                  [5],
#                  [8]])
````
 🧠📐


# Description d’une matrice

On veut connaître la forme, la taille et les dimensions d’une matrice.

On utilise les attributs ``shape``, ``size`` et ``ndim`` d’un objet NumPy :


In [24]:
# Créer une matrice
matrice = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Afficher le nombre de lignes et de colonnes
matrice.shape  # Résultat : (3, 4)

(3, 4)

In [25]:
# Afficher le nombre total d’éléments (lignes × colonnes)
matrice.size  # Résultat : 12

12

In [26]:
# Afficher le nombre de dimensions
matrice.ndim  # Résultat : 2

2

Cela peut paraître basique (et ça l’est), mais c’est extrêmement utile pour :
- vérifier la cohérence des opérations qu'on fais sur les matrices
- comprendre la structure des données
- anticiper les erreurs liées à des formes incompatibles
Que ce soit en phase de débogage, de préparation de données, ou simplement en train de valider les calculs, ces attributs sont des alliés précieux dans l’univers de NumPy.


# Application de fonctions à chaque élément

On veut appliquer une fonction à tous les éléments d’un tableau.

On utilise la méthode vectorize de NumPy :


In [27]:
# Créer une matrice
matrice = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Créer une fonction qui ajoute 100 à un élément
ajouter_100 = lambda i: i + 100

# Créer une fonction vectorisée
fonction_vectorisée = np.vectorize(ajouter_100)

# Appliquer la fonction à tous les éléments de la matrice
fonction_vectorisée(matrice)

# Résultat :
# array([[101, 102, 103],
#        [104, 105, 106],
#        [107, 108, 109]])

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

La méthode ``vectorize`` de NumPy permet de convertir une fonction en une fonction qui peut s’appliquer à chaque élément d’un tableau (ou d’un sous-tableau).
Cependant, il est important de noter que ``vectorize`` fonctionne comme une boucle ``for`` sur les éléments et n’améliore pas les performances.

NumPy permet aussi d’appliquer des opérations directement sur les tableaux, grâce à un mécanisme appelé **broadcasting**.

Par exemple, on peut simplifier la solution précédente :
````python
# Ajouter 100 à tous les éléments
matrice + 100

# Résultat :
# array([[101, 102, 103],
#        [104, 105, 106],
#        [107, 108, 109]])
````

🌀 Broadcasting ne fonctionne pas dans toutes les situations ni avec toutes les formes de tableaux, mais c’est une méthode courante et puissante pour effectuer des opérations simples sur chaque élément d’un tableau NumPy.

💡🐍


# Trouver les valeurs maximale et minimale

On souhaite avoir la valeur maximale ou minimale dans un tableau.

On utilise les méthodes ``max`` et ``min`` de NumPy :


In [28]:
# Créer une matrice
matrice = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Retourner l’élément maximal
np.max(matrice)  # Résultat : 9

np.int64(9)

In [29]:
# Retourner l’élément minimal
np.min(matrice)  # Résultat : 1

np.int64(1)

Il est fréquent de vouloir connaître la valeur maximale ou minimale dans un tableau ou dans une portion du tableau. Pour cela, on utilise simplement les méthodes ``max`` et ``min``.

Grâce au paramètre ``axis``, on peut appliquer ces opérations selon un axe particulier :
````python
# Trouver l’élément maximal de chaque colonne
np.max(matrice, axis=0)  # Résultat : array([7, 8, 9])

# Trouver l’élément maximal de chaque ligne
np.max(matrice, axis=1)  # Résultat : array([3, 6, 9])
````

📌 À noter :
- ``axis=0`` signifie qu’on applique la fonction verticalement, c’est-à-dire sur chaque colonne.
- ``axis=1`` signifie qu’on applique la fonction horizontalement, c’est-à-dire sur chaque ligne.


# Calcul de la moyenne, de la variance et de l’écart type

On veut calculer des statistiques descriptives sur un tableau.

On utilise les fonctions ``mean``, ``var`` et ``std`` de NumPy :

In [30]:
# Créer une matrice
matrice = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Calculer la moyenne
np.mean(matrice)  # Résultat : 5.0

np.float64(5.0)

In [31]:
# Calculer la variance
np.var(matrice)  # Résultat : 6.666666666666667

np.float64(6.666666666666667)

In [32]:
# Calculer l’écart type
np.std(matrice)  # Résultat : 2.5819888974716112

np.float64(2.581988897471611)

Comme avec max et min, on peut facilement extraire des statistiques descriptives sur l’ensemble d’un tableau ou bien selon un axe spécifique :
````python
# Calculer la moyenne de chaque colonne
np.mean(matrice, axis=0)  # Résultat : array([4., 5., 6.])
````

📌 Rappel utile :
- ``axis=0`` applique l’opération colonne par colonne (verticalement).
- ``axis=1`` l’applique ligne par ligne (horizontalement).


# Remodeler des tableaux

On veut modifier la forme (nombre de lignes et de colonnes) d’un tableau sans en changer les valeurs.

Pour ce faire, on utilise la fonction ``reshape`` de NumPy :


In [33]:
# Créer une matrice 4x3
matrice = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

# Remodeler la matrice en une matrice 2x6
matrice.reshape(2, 6)

# Résultat :
# array([[ 1, 2, 3, 4, 5, 6],
#        [ 7, 8, 9, 10, 11, 12]])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

La fonction reshape permet de restructurer un tableau, en conservant toutes les données mais en modifiant leur disposition (lignes et colonnes).

📌 Condition importante :
Le nombre d’éléments dans la matrice d’origine et la nouvelle forme doit être identique.
On peut vérifier le nombre d’éléments avec :

````python
matrice.size  # Résultat : 12
````

Une option très pratique est d’utiliser -1 comme argument pour signifier « autant que nécessaire » :

````python
# Une ligne, autant de colonnes que nécessaire
matrice.reshape(1, -1)

# Résultat :
# array([[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])
````

Et si tu donnes un seul entier, tu obtiens un tableau unidimensionnel :
````python
matrice.reshape(12)

# Résultat :
# array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
````

# Transposer un vecteur ou une matrice

On souhaite transposer un vecteur ou une matrice.

On utilise donc la méthode ``.T`` :


In [34]:
# Créer une matrice
matrice = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Transposer la matrice
matrice.T

# Résultat :
# array([[1, 4, 7],
#        [2, 5, 8],
#        [3, 6, 9]])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

La transposition est une opération courante en algèbre linéaire qui consiste à échanger les lignes et les colonnes d’une matrice.

📌 À savoir :

Techniquement, un vecteur simple (comme ``np.array([1, 2, 3])``) ne peut pas être transposé car c’est simplement une liste de valeurs sans orientation (ni ligne ni colonne). Par exemple :

````python
# Transposer un vecteur simple
np.array([1, 2, 3, 4, 5, 6]).T  # Résultat : array([1, 2, 3, 4, 5, 6])
````

Mais si on crée explicitement un vecteur ligne, on peut le transposer en vecteur colonne :

````python
# Transposer un vecteur ligne en vecteur colonne
np.array([[1, 2, 3, 4, 5, 6]]).T

# Résultat :
# array([[1],
#        [2],
#        [3],
#        [4],
#        [5],
#        [6]])
````

Et bien sûr, cela fonctionne aussi dans l’autre sens.


# 🧮 Aplatir une matrice

Il est question ici de transformer une matrice en tableau à une seule dimension.

Pour cela, on utilise la méthode ``flatten`` :


In [3]:
# Créer la matrice
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Aplatir la matrice
matrix.flatten()
# Résultat : array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

``flatten`` est une méthode simple qui permet de transformer une matrice en un tableau à une dimension.

➡️ Alternativement, on peut utiliser ``reshape`` pour créer un vecteur ligne :
````python
matrix.reshape(1, -1)
# Résultat : array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
````

➡️ Une autre méthode courante est ``ravel``. Contrairement à ``flatten``, qui retourne une copie du tableau original, ``ravel`` travaille directement sur l’objet existant, ce qui le rend légèrement plus rapide. Elle permet aussi d’aplatir une liste de tableaux, ce que ``flatten`` ne peut pas faire. Cette opération est donc utile pour les très grands tableaux et pour optimiser le code :

````python
# Créer une première matrice
matrix_a = np.array([[1, 2],
                     [3, 4]])

# Créer une seconde matrice
matrix_b = np.array([[5, 6],
                     [7, 8]])

# Créer une liste de matrices
matrix_list = [matrix_a, matrix_b]

# Aplatir toute la liste de matrices
np.ravel(matrix_list)
# Résultat : array([1, 2, 3, 4, 5, 6, 7, 8])

````




# 📏 Déterminer le rang d'une matrice

On est amener à connaître le rang d'une matrice.

Pour cela , on utilise la méthode ``matrix_rank`` de l'algèbre linéaire de NumPy :


In [4]:
# Créer la matrice
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# Retourner le rang de la matrice
np.linalg.matrix_rank(matrix)
# Résultat : 2

np.int64(2)

Le **rang** d'une matrice correspond aux dimensions de l’espace vectoriel engendré par ses colonnes ou ses lignes.
Mieux, le nombre de vecteurs colonnes/lignes de la matrice qui sont linéairement indépendants.
Grâce à la fonction ``matrix_rank`` dans NumPy, déterminer ce rang devient très simple.


# 🔢 Extraire la diagonale d'une matrice

On est amener parfois à extraire les éléments diagonaux d'une matrice.

Donc, on utilise la méthode ``diagonal`` de NumPy :


In [5]:
# Créer la matrice
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Retourner les éléments diagonaux
matrix.diagonal()
# Résultat : array([1, 4, 9])

array([1, 4, 9])

NumPy rend l’extraction des éléments diagonaux très simple grâce à la méthode ``diagonal``.`

➡️ Il est également possible d’obtenir une diagonale décalée par rapport à la diagonale principale en utilisant le paramètre ``offset`` :
````python
# Diagonale une position au-dessus de la principale
matrix.diagonal(offset=1)
# Résultat : array([2, 6])

# Diagonale une position en dessous de la principale
matrix.diagonal(offset=-1)
# Résultat : array([2, 8])
````





# ➕ Calculer la trace d'une matrice

On souhaite calculer la trace d'une matrice.

On utilise la méthode ``trace`` :


In [6]:
# Créer la matrice
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Retourner la trace de la matrice
matrix.trace()
# Résultat : 14

np.int64(14)

La trace d'une matrice est la somme des éléments diagonaux. Elle est souvent utilisée dans des méthodes d'apprentissage automatique.

➡️ Avec un tableau multidimensionnel NumPy, on peut utiliser directement ``trace``.

➡️ Alternativement, on peut extraire les éléments diagonaux avec ``diagonal()`` et en faire la somme :
````python
# Extraire la diagonale et sommer les éléments
sum(matrix.diagonal())
# Résultat : 14
````





# 🔘 Calcul du produit scalaire de deux vecteurs

On doit calculer ici le produit scalaire de deux vecteurs.

Pour ce faire, on utilise la fonction ``dot`` de NumPy :


In [7]:
# Créer deux vecteurs
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Calculer le produit scalaire
np.dot(vector_a, vector_b)
# Résultat : 32

np.int64(32)

Le produit scalaire de deux vecteurs, a et b, est défini comme :

$\sum_{i=1}^{n} a_i \cdot b_i$

où $a_i$ est le i-ème élément du vecteur a, et $b_i$ celui du vecteur b.

➡️ Avec NumPy, on peut utiliser ``dot`` pour le calculer facilement.

➡️ Depuis Python 3.5+, on peut aussi utiliser l’opérateur ``@`` :
````python
# Calculer le produit scalaire avec l’opérateur @
vector_a @ vector_b
# Résultat : 32
````





# ➕➖ Addition et soustraction de matrices

On souhaite additionner ou soustraire deux matrices.

On utilise les fonctions ``add`` et ``subtract`` de NumPy :


In [8]:
# Créer la première matrice
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Créer la deuxième matrice
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Additionner les deux matrices
np.add(matrix_a, matrix_b)
# Résultat : array([[ 2, 4, 2],
#                   [ 2, 4, 2],
#                   [ 2, 4, 10]])


array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [9]:

# Soustraire les deux matrices
np.subtract(matrix_a, matrix_b)
# Résultat : array([[ 0, -2, 0],
#                   [ 0, -2, 0],
#                   [ 0, -2, -6]])

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

On peut aussi utiliser les opérateurs ``+`` et ``–`` pour faire la même chose de manière plus concise :
````python
# Additionner deux matrices
matrix_a + matrix_b
# Résultat : array([[ 2, 4, 2],
#                   [ 2, 4, 2],
#                   [ 2, 4, 10]])
````

ℹ️ Il faudrait s'assurer que les matrices ont les mêmes dimensions, sinon NumPy lèvera une erreur.


# ✖️ Multiplication de matrices

On souhaite effectuer une multiplication entre deux matrices.

Donc, on utilise la fonction ``dot`` de NumPy :


In [10]:
# Créer la première matrice
matrix_a = np.array([[1, 1],
                     [1, 2]])

# Créer la seconde matrice
matrix_b = np.array([[1, 3],
                     [1, 2]])

# Effectuer la multiplication matricielle
np.dot(matrix_a, matrix_b)
# Résultat : array([[2, 5],
#                   [3, 7]])

array([[2, 5],
       [3, 7]])

➡️ Depuis Python 3.5+, on peut utiliser l'opérateur ``@`` pour une syntaxe plus intuitive :

````python
# Multiplication matricielle avec l'opérateur @
matrix_a @ matrix_b
# Résultat : array([[2, 5],
#                   [3, 7]])
````

➡️ Pour effectuer une multiplication élément par élément (et non une multiplication matricielle), on utilise l'opérateur ``*`` :

````python
# Multiplication élément par élément
matrix_a * matrix_b
# Résultat : array([[1, 3],
#                   [1, 4]])
````

ℹ️ La multiplication matricielle suit les règles de l’algèbre linéaire classique :

Le nombre de colonnes dans la première matrice doit correspondre au nombre de lignes dans la seconde.


# 🔁 Inversion d'une matrice carrée

On souhaite calculer l’inverse d’une matrice carrée.

Pour cela, on utilise la méthode ``inv`` du module ``linalg`` de NumPy :


In [11]:
# Créer une matrice carrée
matrix = np.array([[1, 4],
                   [2, 5]])

# Calculer l'inverse de la matrice
np.linalg.inv(matrix)
# Résultat : array([[-1.66666667,  1.33333333],
#                  [ 0.66666667, -0.33333333]])

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

L’**inverse** d’une matrice carrée $A$ est une matrice $A^{-1}$ telle que :

$A \cdot A^{-1} = I$

où $I$ est la matrice identité.

➡️ NumPy permet de calculer cette matrice inverse grâce à ``np.linalg.inv()`` si l’inverse existe (c’est-à-dire si la matrice est non singulière).

📌 Pour vérifier, on peut multiplier la matrice par son inverse :
````python
# Multiplier la matrice par son inverse
matrix @ np.linalg.inv(matrix)
# Résultat : array([[1., 0.],
#                   [0., 1.]])
````

Cela donne bien la matrice identité, preuve que l’inversion a réussi.


# 🎲 Génération de valeurs aléatoires

On souhaite générer des valeurs pseudo-aléatoires.

Pour cela, il faudrait utiliser le module ``random`` de NumPy :


In [12]:
# Définir une graine (seed) pour rendre les résultats reproductibles
np.random.seed(0)

# Générer trois nombres flottants aléatoires entre 0.0 et 1.0
np.random.random(3)
# Résultat : array([0.5488135 , 0.71518937, 0.60276338]) ---> on a utilisé la graine 0 pour que les résultats soient toujours les mêmes
# (si on ne met pas de graine, les résultats seront différents à chaque exécution

array([0.5488135 , 0.71518937, 0.60276338])

NumPy offre une grande variété de fonctions pour générer des nombres aléatoires — bien plus que ce qu’on peut couvrir ici.

✅ Exemple de génération d’entiers aléatoires :
````python
# Générer trois entiers aléatoires entre 0 et 10 inclus
np.random.randint(0, 11, 3)
# Résultat : array([3, 7, 9])
````

✅ Tirage depuis des distributions statistiques (attention, ce n’est pas techniquement aléatoire, mais basé sur des lois probabilistes) :
````python
# Tirage dans une distribution normale (moyenne = 0.0, écart-type = 1.0)
np.random.normal(0.0, 1.0, 3)
# Résultat : array([-1.42232584, 1.52006949, -0.29139398])

# Tirage dans une distribution logistique (moyenne = 0.0, échelle = 1.0)
np.random.logistic(0.0, 1.0, 3)
# Résultat : array([-0.98118713, -0.08939902, 1.46416405])

# Tirage uniforme entre 1.0 inclus et 2.0 exclus
np.random.uniform(1.0, 2.0, 3)
# Résultat : array([1.47997717, 1.3927848 , 1.83607876])
````

🔁 Pour que les résultats soient prévisibles et reproductibles, on utilise la graine (seed) du générateur. Deux exécutions avec la même graine produisent les mêmes résultats, ce qui est très pratique pour les tests ou les tutoriels.


# Création des données avec numpy 

## Créer un numpy array avec une liste/liste de liste (matrice)

In [13]:
# Création à partir d'un liste
liste = [1, 2, 3, 4, 5]  # Définition de la liste d'élément
array_with_liste = np.array(liste)
print(array_with_liste)  # affiche le numpy array

[1 2 3 4 5]


In [14]:
# Création à partir d'une matrice
# Création d'un numpy array à partir d'une liste de listes (matrice)
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_with_matrice = np.array(matrice)
print(array_with_matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Créer un numpy array à partir des fonctions intégrées

In [ ]:
#Créer un numpy array à partir de la fonction zeros
array_zeros = np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Créer un numpy array à partir de la fonction ones
array_ones = np.ones((4,2))
print(array_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Créer un numpay array avec la fonction eye 
array_eye = np.eye(3) #Pour créer la matrice identité
array_eye


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Créer un numpay array avec la fonction arange: pour créer des nombre entre le minimum et le maximum avec un pas
array_arange = np.arange(0, 11, 2) # Pour créer un tableau de 0 à 10 avec un pas de 2
array_arange

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
#Créer un numpay array avec la fonction linspace 
#générer une séquence de nombre 
#entre deux valeurs données avec un nombre de points donné
#Très utile pour les graphiques
array_linspace = np.linspace(0, 1, 10) # Pour créer un tableau de 0 à 1 avec 10 points exacts
array_linspace

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
# Créer un numpy array de valeurs aléatoires avec la fonction random
# Utile pour initialiser les poids dans les réseaux de neurones, générer des données d'apprentissage synthétiques
array_random = np.random.random((5,4)) # Pour créer un tableau de 5 lignes et 4 colonnes avec des valeurs aléatoires comprises entre 0 et 1
print(array_random)

[[0.38460183 0.91191777 0.26433874 0.42778659]
 [0.86015894 0.33599314 0.07096604 0.53405233]
 [0.38777336 0.92685784 0.37362457 0.37665129]
 [0.66224501 0.04220367 0.09486011 0.24925666]
 [0.29675815 0.27890915 0.4802953  0.13089389]]


On peut utiliser aussi : 

-  ``np.random.rand(5,4)`` pour créer un tableau de 5 lignes et 4 colonnes avec des valeurs aléatoires comprises entre 0 et 1

-  ``np.random.randn(5,4)`` pour créer un tableau de 5 lignes et 4 colonnes avec des valeurs aléatoires suivant une distribution normale

-  ``np.random.randint(0, 10, (5,4))`` pour créer un tableau de 5 lignes et 4 colonnes avec des valeurs aléatoires entières entre 0 et 10

-  ``np.random.choice([1, 2, 3, 4, 5], size=(5,4))`` pour créer un tableau de 5 lignes et 4 colonnes avec des valeurs aléatoires 
choisies parmi une liste

-  ``np.random.permutation([1, 2, 3, 4, 5])`` pour créer un tableau de 5 éléments avec des valeurs aléatoires choisies parmi une liste

-  ``np.random.shuffle([1, 2, 3, 4, 5])`` pour mélanger les éléments d'une liste

- ``np.random.choice([1, 2, 3, 4, 5], size=(5,4), replace=True)`` pour créer un tableau de 5 lignes et 4 colonnes avec des valeurs aléatoires choisies parmi une liste avec remplacement

-  ``np.random.choice([1, 2, 3, 4, 5], size=(5,4), replace=False)`` pour créer un tableau de 5 lignes et 4 colonnes avec des valeurs aléatoires choisies parmi une liste sans remplacement

- `` np.random.uniform(0, 1, (5,4))``  Pour créer un tableau de 5 lignes et 4 colonnes avec des valeurs aléatoires comprises entre 0 et 1

- ``np.random.normal(0, 1, (5,4))``  Pour créer un tableau de 5 lignes et 4 colonnes avec des valeurs aléatoires suivant une distribution normale  de moyenne=0.0 et ecart-type=1.0 


# Fonctions mathématiques et statistiques avec Numpy

In [ ]:
#Fonction mathématiques basiques
array1=array_with_liste
array_sum = np.sum(array1)
array_mean = np.mean(array1)
array_std = np.std(array1)
array_min = np.min(array1)
array_max = np.max(array1)
array_sqrt = np.sqrt(array1)
array_abs = np.abs(array1)
array_power = np.power(array1, 2)
array_exp = np.exp(array1)
array_log = np.log(np.abs(array1))
array_sin = np.sin(array1)
array_median = np.median(array1)
array_sum

15

In [ ]:
array_median

3.0

# Manipulation des matrices avec Numpy

In [ ]:
# Produit matriciel
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
produit_matriciel = np.dot(array_with_matrice, array_with_matrice)
print(produit_matriciel)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
# Transposée
transposee = np.transpose(array_with_matrice)
print(transposee)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# Inversion (pour les matrices carrées non singulières)
inverse = np.linalg.inv(array_eye)
print(inverse)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Déterminant
determinant=np.linalg.det(array_eye)
print(determinant)  

1.0


# Accéder  aux éléments, sélectionner, modifier et mettre à jour un numpy array

In [ ]:
# Accès aux éléments
array1 = np.array([1,2,3,4,5]) 
premier_element = array1[0]
print(premier_element)


1


In [ ]:
array1[2]

3

In [ ]:
# Modification d'un élément
array1[0] = 15
print(array1)

[15  2  3  4  5]


In [ ]:
# Sélection des éléments qui respectent une condition
condition = array1 > 5 # Sélectionne les éléments supérieurs à 5
elements_respectant_condition = array1[array1 > 2] # Assigne à une nouvelle variable les élements qui respectent la condition
elements_respectant_condition

array([15,  3,  4,  5])

In [ ]:
condition = array1 > 3
condition
indices = np.where(array1 > 3) # pour obtenir les indices des éléments qui respectent la condition
indices

(array([0, 3, 4]),)

In [ ]:
array1 > 5 # affiche un tableau de true/false pour chaque élément du tableau array vérifiant la condition (True) ou non (False) 

array([ True, False, False, False, False])

In [ ]:
# Utilisation de np.where
indices = np.where(array1 > 5)
elements_respectant_condition_np_where = array1[indices]
print(elements_respectant_condition_np_where)

In [ ]:
# Mise à jour d'un numpy array
array1[condition] = 0 # Met à zéro les éléments qui respectent la condition
print(array1)

[0 2 3 0 0]


In [ ]:
#  Slicing et indexation avancée
array6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing
premiere_ligne = array6[0, :]
premiere_ligne

array([1, 2, 3])

In [ ]:
#Première colonne
premiere_colonne = array6[:, 0]
premiere_colonne


array([1, 4, 7])

In [ ]:
#sous matrice
sous_matrice = array6[1:3, 1:3]
sous_matrice

array([[5, 6],
       [8, 9]])

In [ ]:
# Indexation avancée
lignes = [0, 1]
colonnes = [1, 2]
elements_selectionnes = array6[lignes, colonnes]
elements_selectionnes

array([2, 6])

In [ ]:
# Opérations élémentaires et diffusion (broadcasting)
array7 = np.array([1, 2, 3])
array8 = np.array([4, 5, 6])


# Addition élémentaire
array_addition = array7 + array8
array_addition

array([5, 7, 9])

In [ ]:
# Multiplication élémentaire
array_multiplication = array7 * array8
array_multiplication


array([ 4, 10, 18])

In [ ]:
# Diffusion (broadcasting)
array9 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array10 = np.array([1, 2, 3])
array9+array10

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

# Redimensionnement, append, type de données taille etc

In [ ]:
#r redimensionné le numpy array
array3 = np.arange(9)
array3_redimensionne = array3.reshape((3, 3))
print(array3_redimensionne)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
array3 = np.arange(9)
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#Ajouter des éléments dans un numpy array
array1_allonge = np.append(array1, [6, 7, 8])
print(array1_allonge)

[0 2 3 0 0 6 7 8]


In [ ]:
#Connaitre les caractéristiques d'un numpy array
array_with_matrice.shape #dimension de l'array 

(3, 3)

In [ ]:
#Connaitre le type de l'objet
type(array_with_matrice) #type de l'objet

numpy.ndarray

In [ ]:
#Connaitre le type des él
array1.dtype #type des objets contenu dans le numpy array

dtype('int64')

In [ ]:
array7 = np.array(['1', '2', '3'])
array7.dtype

dtype('<U1')